Rack interface
the-action-man/tn-rack-interface pull request #1
Opened 2021-06-22 02:10 UTC by the-action-man

<img width="837" alt="изображение" src="https://user-images.githubusercontent.com/49880822/122851734-28ac7a00-d318-11eb-83e8-37ada39f1fac.png">

2021-06-27 20:20 UTC, VidgarVii commented on rack/time.rb
> +class Time
класс Time встроен в ruby. Сейчас ты полностью его переопределяешь, что может привести к неожиданным багам в ПО.

2021-06-27 20:20 UTC, VidgarVii commented on rack/time.rb
> +# require 'headers'
подобные комментарии мусор. Надо удалить

2021-06-27 20:20 UTC, VidgarVii commented on rack/time.rb
> +    [400, headers, ["Unknown time format #{unknown_formats}"]]
Сейчас у тебя логика размазана, м/у классами. За создание ответа сервера пусть отвечает App.
А тут оставь только работу с датой.
Вспоминай как работал с сервисами в RoR

2021-06-27 20:20 UTC, VidgarVii commented on rack/time.rb
> +    [200, headers, [Time.now.strftime(format)]]
вот и сам попал в свой же баг. Какой Time тут вызывается?

2021-06-27 20:20 UTC, VidgarVii commented on rack/time.rb
> +  end
бесполезные метод. Куда понятней вызывать внутри класса инстанс переменную. Так будет понятней с какими данными работаешь. Если так нравятся методы. То можно использоваться attr_reader.

2021-06-27 20:20 UTC, VidgarVii commented on rack/time.rb
> +    Headers::HEADERS
1 Для настройки ContentType по умолчанию можно воспользоваться настройкой через Rack::ContentType
2 классу который работает со временем не надо знать о построении ответа сервера. Ты же не будешь звать сатезника чинить электрику. Эти банальные и простые правила надо соблюдать и в ОО программировании

2021-06-27 20:20 UTC, VidgarVii commented on rack/time.rb
> +  end
очень длинные методы... 5-7 строк. 10 максимум. Абстрагируй код на мелкие методы. Честно говоря почти не понятно что тут вообще происходит
бесконечный цикл без предусловия может привести к багу. Очень рискованный код

2021-06-27 20:20 UTC, VidgarVii commented on rack/time.rb
> +  end
везде прослеживается императивный подход в написании кода. 
```
def method(collection)
  result = []
  collection.each { |var| result << item if condition}
  result
```
1 В руби есть множество методов написание декларативного кода. map select detect и т.д. ООП это про декларативность!
У тебя сейчас дико заполняется оперативная память мусорными данными

2021-06-27 20:20 UTC, VidgarVii commented on rack/headers.rb
> +end
используй Rack::ContentType

2021-06-27 20:20 UTC, VidgarVii commented on rack/config.ru
> +
тут достаточно подключать app
А вот app пусть подключает всё что ему требуется.
Потом научишься писать конструкторы ПО и делегировать подключение файлов отдельно в модуль 
А сейчас не понятно зачем все эти require_relative если используется тольк app

2021-06-27 20:20 UTC, VidgarVii commented on rack/app.rb
> +    Rack::Response.new(["oops"], 404, headers).finish
для роутинга можно было использовать Rack::URLMap
для 1 энд пойнта идеальный вариант

2021-06-27 20:20 UTC, VidgarVii commented on rack/app.rb
> +    return time.call if req.path == ("/time") && req.get?
для роутинга можно было использовать Rack::URLMap
для 1 энд пойнта идеальный вариант

2021-06-27 20:20 UTC, VidgarVii commented on rack/app.rb
> +
нет проверки успеха формирования ответа сервиса

2021-06-27 23:35 UTC, the-action-man commented on rack/time.rb
> +class Time
renamed

2021-06-27 23:35 UTC, the-action-man commented on rack/time.rb
> +# require 'headers'
removed

2021-06-27 23:36 UTC, the-action-man commented on rack/config.ru
> +
done

2021-06-28 01:01 UTC, the-action-man commented on rack/app.rb
> +    Rack::Response.new(["oops"], 404, headers).finish
added

2021-06-28 01:02 UTC, the-action-man commented on rack/app.rb
> +    return time.call if req.path == ("/time") && req.get?
added

2021-06-28 01:02 UTC, the-action-man commented on rack/headers.rb
> +end
removed

2021-06-28 01:02 UTC, the-action-man commented on rack/time.rb
> +  end
removed

2021-06-28 01:03 UTC, the-action-man commented on rack/time.rb
> +    [200, headers, [Time.now.strftime(format)]]
improved

2021-06-28 01:04 UTC, the-action-man commented on rack/time.rb
> +    [400, headers, ["Unknown time format #{unknown_formats}"]]
improved

2021-06-28 01:06 UTC, the-action-man commented on rack/app.rb
> +
видимо не актуально так как все переделал

2021-06-28 01:07 UTC, the-action-man commented on rack/time.rb
> +    Headers::HEADERS
improved

2021-06-28 02:06 UTC, the-action-man commented on rack/time.rb
> +  end
переделал

2021-06-28 11:16 UTC, VidgarVii requested changes

2021-06-28 11:16 UTC, VidgarVii commented on rack/current_time_controller.rb
> +  START_SYMBOL_OF_QUERY_VALUE = 7.freeze
цифры уже заморожены

2021-06-28 11:16 UTC, VidgarVii commented on rack/current_time_controller.rb
> +class CurrentTimeController
отдельно создавать контроллер не нужен. Он сам по себе вызывая только 1 сервис избыточен.  App уже принимает запрос и отдаёт ответ. И он же знаёт кого надо дёргать для решения конкретной задачи.
Еще раз пишу. Достаточно иметь 2 класса. Аpp где отвечает за техническую работу ПО. (он и будет служить контроллером)
И класс сервис, который будет принимать распарсенные параметры запроса и отдавать ответ

2021-06-28 11:16 UTC, VidgarVii commented on rack/time_util.rb
> +    end
нет декларативности. Опять императивный подход.
Тут явно может подойти метод select вместо each

2021-06-28 17:46 UTC, the-action-man commented on rack/current_time_controller.rb
> +  START_SYMBOL_OF_QUERY_VALUE = 7.freeze
freeze is removed

2021-06-28 17:56 UTC, the-action-man commented on rack/time_util.rb
> +    end
refactored

2021-06-28 18:11 UTC, the-action-man commented on rack/current_time_controller.rb
> +class CurrentTimeController
remove current_time_controller.rb

2021-07-01 16:18 UTC, merged